// lib/utils/images/tiles.dart

final Map<String, String> classToFile = {
  "1D": "assets/images/tiles/card_1d.png",
  "2D": "assets/images/tiles/card_2d.png",
  "3D": "assets/images/tiles/card_3d.png",
  "4D": "assets/images/tiles/card_4d.png",
  "5D": "assets/images/tiles/card_5d.png",
  "6D": "assets/images/tiles/card_6d.png",
  "7D": "assets/images/tiles/card_7d.png",
  "8D": "assets/images/tiles/card_8d.png",
  "9D": "assets/images/tiles/card_9d.png",
  "1B": "assets/images/tiles/card_1b.png",
  "2B": "assets/images/tiles/card_2b.png",
  "3B": "assets/images/tiles/card_3b.png",
  "4B": "assets/images/tiles/card_4b.png",
  "5B": "assets/images/tiles/card_5b.png",
  "6B": "assets/images/tiles/card_6b.png",
  "7B": "assets/images/tiles/card_7b.png",
  "8B": "assets/images/tiles/card_8b.png",
  "9B": "assets/images/tiles/card_9b.png",
  "1C": "assets/images/tiles/card_1c.png",
  "2C": "assets/images/tiles/card_2c.png",
  "3C": "assets/images/tiles/card_3c.png",
  "4C": "assets/images/tiles/card_4c.png",
  "5C": "assets/images/tiles/card_5c.png",
  "6C": "assets/images/tiles/card_6c.png",
  "7C": "assets/images/tiles/card_7c.png",
  "8C": "assets/images/tiles/card_8c.png",
  "9C": "assets/images/tiles/card_9c.png",
  "EW": "assets/images/tiles/card_ew.png",
  "SW": "assets/images/tiles/card_sw.png",
  "WW": "assets/images/tiles/card_ww.png",
  "NW": "assets/images/tiles/card_nw.png",
  "WD": "assets/images/tiles/card_wd.png",
  "GD": "assets/images/tiles/card_gd.png",
  "RD": "assets/images/tiles/card_rd.png",
};
