const Map<String, String> yakuTranslation = {
  "Tsumo": "自摸",
  "Riichi": "立直",
  "OpenRiichi": "明立直",
  "Ippatsu": "一發",
  "Chankan": "搶槓",
  "Rinshan": "嶺上開花",
  "Haitei": "海底撈月",
  "Houtei": "河底撈魚",
  "DaburuRiichi": "雙立直",
  "DaburuOpenRiichi": "雙明立直",
  "NagashiMangan": "流局滿貫",
  "Renhou": "人和",
  "PinfuTsumo": "平和自摸",
  "Menzen Tsumo": "門前清自摸和",

  "Pinfu": "平和",
  "Tanyao": "斷么九",
  "Iipeiko": "一杯口",
  "Haku": "白",
  "Hatsu": "發",
  "Chun": "中",

  "YakuhaiEast": "役牌 東",
  "YakuhaiSouth": "役牌 南",
  "YakuhaiWest": "役牌 西",
  "YakuhaiNorth": "役牌 北",
  "Yakuhai (wind of place)": "場風",
  "Yakuhai (wind of round)": "自風",

  "Sanshoku": "三色同順",
  "Ittsu": "一氣通貫",
  "Chantai": "全帶幺九",
  "Honroto": "混老頭",
  "Toitoi": "對對和",
  "Sanankou": "三暗刻",
  "SanKantsu": "三槓子",
  "SanshokuDoukou": "三色同刻",
  "Chiitoitsu": "七對",
  "Shosangen": "小三元",

  "Honitsu": "混一色",
  "Junchan": "純全帶幺九",
  "Ryanpeikou": "二盃口",

  "Chinitsu": "清一色",

  "KokushiMusou": "國士無雙",
  "ChuurenPoutou": "九蓮寶燈",
  "Suuankou": "四暗刻",
  "Daisangen": "大三元",
  "Shousuushii": "小四喜",
  "Ryuuiisou": "綠一色",
  "Suukantsu": "四槓子",
  "Tsuuiisou": "字一色",
  "Chinroutou": "清老頭",
  "Daisharin": "大車輪",
  "Daichisei": "大七星",

  "DaiSuushii": "大四喜",
  "DaburuKokushiMusou": "雙國士無雙",
  "SuuankouTanki": "四暗刻單騎",
  "DaburuChuurenPoutou": "雙九蓮寶燈",

  "Tenhou": "天和",
  "Chiihou": "地和",
  "RenhouYakuman": "人和役滿",
  "Sashikomi": "槍槓",
  "Paarenchan": "八連莊",

  "Dora": "寶牌",
  "AkaDora": "赤寶牌",
};